services:
  mongo:
    image: "mongo:latest"
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: nestjsdb
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27018:27017

  nestjs:
    build: .
    container_name: nestjs-backend
    stop_signal: SIGTERM
    stop_grace_period: 200s
    environment:
      DATABASE_URL: "mongodb://mongoadmin:mongopassword@mongo:27017/nestjsdb?authSource=admin"
      DATABASE_USER: "mongoadmin"
      DATABASE_PASSWORD: "mongopassword"
      JWT_SECRET: "changeme"
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
      AWS_S3_BUCKET: "${AWS_S3_BUCKET}"
      AWS_S3_ACCESS_KEY: "${AWS_S3_ACCESS_KEY}"
      AWS_S3_SECRET_KEY: "${AWS_S3_SECRET_KEY}"
      VIDEO_DEFAULT_BLURRED_URL: "${VIDEO_DEFAULT_BLURRED_URL}"
    ports:
      - 3000:3000
    depends_on:
      mongo:
        condition: service_started
    volumes:
      - nestjs_data_container:/usr/src/app
    
volumes:
  nestjs_data_container:
  mongodb_data_container:
