services:
  mongo:
    image: "mongo:latest"
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: nestjsdb
    volumes:
      - mongodb_data_container:/data/db

  nestjs:
    container_name: nestjs-backend
    build: .
    stop_signal: SIGTERM
    stop_grace_period: 200s
    environment:
      DATABASE_URL: "mongodb://mongoadmin:mongopassword@mongo:27017/nestjsdb?authSource=admin"
      DATABASE_USER: "mongoadmin"
      DATABASE_PASSWORD: "mongopassword"
      JWT_SECRET: "${JWT_SECRET}"
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
      AWS_S3_BUCKET: "${AWS_S3_BUCKET}"
      AWS_S3_ACCESS_KEY: "${AWS_S3_ACCESS_KEY}"
      AWS_S3_SECRET_KEY: "${AWS_S3_SECRET_KEY}"
      VIDEO_DEFAULT_BLURRED_URL: "${VIDEO_DEFAULT_BLURRED_URL}"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
      STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
      APP_FEE: "${APP_FEE}"
    depends_on:
      mongo:
        condition: service_started
    volumes:
      - nestjs_data_container:/usr/src/app
    links:
      - mongo

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: "${CERTBOT_EMAIL}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx:/etc/nginx/user_conf.d
    depends_on:
      nestjs:
        condition: service_started
    links:
      - nestjs
    
volumes:
  nestjs_data_container:
  mongodb_data_container:
  nginx_secrets:
