version: '3.8'

services:
  nestjs:
    container_name: nestjs-backend
    build: .
    stop_signal: SIGTERM
    stop_grace_period: 200s
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      JWT_SECRET: "${JWT_SECRET}"
      MAILGUN_API_KEY: "${MAILGUN_API_KEY}"
      MAILGUN_DOMAIN: "${MAILGUN_DOMAIN}"
      AWS_S3_BUCKET: "${AWS_S3_BUCKET}"
      AWS_S3_ACCESS_KEY: "${AWS_S3_ACCESS_KEY}"
      AWS_S3_SECRET_KEY: "${AWS_S3_SECRET_KEY}"
      VIDEO_DEFAULT_BLURRED_URL: "${VIDEO_DEFAULT_BLURRED_URL}"
    volumes:
      - nestjs_data_container:/usr/src/app

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: "${CERTBOT_EMAIL}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx:/etc/nginx/user_conf.d
    depends_on:
      nestjs:
        condition: service_started
    links:
      - nestjs
    
volumes:
  nestjs_data_container:
  nginx_secrets:
